-- Straight Outta: initial schema
-- Regions (West, Midwest, South, East) -> locations -> artists; years (time frames); playlists by location + optional year.

-- Regions
CREATE TABLE regions (
  id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

-- Locations (sub-regions per region)
CREATE TABLE locations (
  id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  region_id INTEGER NOT NULL REFERENCES regions (id) ON DELETE CASCADE,
  name      TEXT NOT NULL,
  UNIQUE (region_id, name)
);

CREATE INDEX idx_locations_region_id ON locations (region_id);

-- Artists per location
CREATE TABLE artists (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id INTEGER NOT NULL REFERENCES locations (id) ON DELETE CASCADE,
  name        TEXT NOT NULL
);

CREATE INDEX idx_artists_location_id ON artists (location_id);

-- Time frames (e.g. "90s" -> 1990–1999)
CREATE TABLE years (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  start_year INTEGER NOT NULL,
  end_year   INTEGER NOT NULL
);

-- Playlists: Spotify playlist per location and optional time frame (years_id NULL = "all time")
CREATE TABLE playlists (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id INTEGER NOT NULL REFERENCES locations (id) ON DELETE CASCADE,
  playlist_id TEXT NOT NULL,
  years_id    INTEGER REFERENCES years (id) ON DELETE SET NULL
);

CREATE INDEX idx_playlists_location_id ON playlists (location_id);
CREATE INDEX idx_playlists_years_id ON playlists (years_id);

-- At most one "all time" playlist per location
CREATE UNIQUE INDEX idx_playlists_location_all_time
  ON playlists (location_id) WHERE years_id IS NULL;
